### ISSUE TITLE
generate.py文件报错 IOError: Unable to open file

### ISSUE THREAD

**Issue by ghost** [tongpi/synthtext100kCH#4]
请问你们都遇到这个问题了吗

Traceback (most recent call last):
  File "generate_h5.py", line 68, in <module>
    merge_h5(input_path, output_path,'dset.h5')
  File "generate_h5.py", line 34, in merge_h5
    depth = h5py.File(file_path, 'r')
  File "/home/zhengjingqing/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 260, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/zhengjingqing/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 89, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2579)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2538)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/home/ilan/minonda/conda-bld/work/h5py/h5f.c:1816)
IOError: Unable to open file (Truncated file: eof = 15030288384, sblock->base_addr = 0, stored_eoa = 15807826032)

**Comment by doudoubean** [comment]
看看你的文件路径是否正确
